// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmBiiaJ9_KosPAjg9ToD8WZnjMVr8j2U',
    appId: '1:588266983110:web:6d36a028057ab5f3af51c7',
    messagingSenderId: '588266983110',
    projectId: 'heyuni-ai',
    authDomain: 'heyuni-ai.firebaseapp.com',
    storageBucket: 'heyuni-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-UMehQdkwmOqfPYTFbB97ujJfbhQMNo0',
    appId: '1:588266983110:android:dff7defba74ca741af51c7',
    messagingSenderId: '588266983110',
    projectId: 'heyuni-ai',
    storageBucket: 'heyuni-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUhJ3JLojkOrLAQjeCOm6qZOtyTS7yi8',
    appId: '1:588266983110:ios:ec218595030febb1af51c7',
    messagingSenderId: '588266983110',
    projectId: 'heyuni-ai',
    storageBucket: 'heyuni-ai.firebasestorage.app',
    iosBundleId: 'com.example.heyuni',
  );
}
